let doraASCII =
`xxxxxkkxxxxxxxxxxxkxxxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddxxxxxxxxxxxko,.;:,;lccc:::::ldoooddxxxkkkkxxxkOOOOOkkxdoooddddxdddddddddddddoooddddddddddddddddddddddddddddxxxxxxxxdddddddddddddddddddddddddddxdddddddddddddddddddddxxddddddddddddddddxdxxddxxxxkkkxxxxxdooolllccccccc
kkxxkkkkkxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkkxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddxxxxxxxxxxxkx;.':,,cccccc:::codoooddxxdxxdddxkkkOOkkxdddoooodddddddddddddxxdooooddddddddddddddddddddxxxxxxxxxxxxxdxxddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxddddddddddddddddddddxxxxxxxxxxxxxxxddddooool
kkxkkxkkxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddxxxxxxxxxxxkkl'';;':lcccc::::odoloooooodoodxdxkkOOkxdddllllooollloooodddddddoooooodddddddddddddddddxxxxxxxxxxxxxdddxdddxdddddddddddddddddddxxdddddddddxxddxxxddddddddxxxxxxxdddddddddddddddddddxxxxxxxxdxxxxdddddddxxx
xxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxddxddddddddddddxxxxxxxxkkxkdl,,:';ccccc:::;cllcclooddddddddddoooooolc:::;;;;,,;;;;;:::cllooddddoddddddddddddxxxxxxxxxxxxxxxxxdxxxxdddxxxdxxdddddddddddxxxxdddddddxxxxxxxxxxxxxxxddddxxxxxxdddddddddddddddddddddxxxkxxxddxxxxdddddddx
xxxxkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxkkkxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxdxxdddddddddddddddxxxxxxxxxx:,:,,cc::::::::looooooooloooooolc:::;,,,'''''''''''''''',,,;;:clodddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddxxddxxxxxdxxxxdxxxdxxxxxxxxxxxxxxddddddddxxxdddddddddddddddddddxxxxxxxdxxxdddddood
xxkkxxxxxxxxxxxxxxxxxxxxxkxxxxxxkkxxkkkkkxkkkkkxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxddxdddddddddddddxxxxxxxxl,;;,::::::::::loolllc::::;::;;;,,'''...................'''''',,;:codddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxdddddxxxxxxxxxxxxxxxxxxxddddxxxxxxddddddddddddddddddxxkkkxxdxxxdddddo
xxxxxxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxkkkkxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxddddddodddddddddxxxxxxxd;,;,;c::cccc::cllc::;;;;,,,;;;,,,''.................'''''''''''''',:loddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxddddddxdddddddddddxkkkkxxxxxddddd
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxkkxkkxxxxddxdddodddddddddddxxddddc,:;,:::c:::::;::;,,,,,,,,,,,,,,,,,'...................'''''''''''..',:lodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxxddddddddddddddddxxkkkxxxxxxxdd
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxkkkkkkxxxxxxdddddddddddddddddddxxkd:::;:c::::;;;,,,,'''''',,,,,,'',,''''''.......................''''''..':ldddxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxxxxxdddddddddddddddddxkkkxxdxxxxd
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkxkkkkkkkkxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxkxkkkkkxxxxxxxxxdddddddddddddddddxxxxxd:;c;;:;;;,,,,,,'''''''','''''''''''''''.'''.......................''''..,coddxxxxxxkkxxxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddxxkkkxxxxxx
xxxxxxxxxxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkxxkkkkxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkxxxxxkxxxxkkxxkkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxkkxxxkkkkkkkkkkkxxxxxxxxxxxxdddxxddddddxxxxddxxl,:c:;,,'',,,,''''''''''''''''''''........................   ........''...,codxxxkxxkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdxxxxxxxddddddddddddddxkkkkxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkxxkxxkxkxkkkxkkkxxkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxdxxxddxxkkkd:;;;;,'''''''''''.''''''''''''............................    .........'...;ldxxxxxxkkkkkkkkkkkxxxkkxxkkkxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddxkkkkxxx
xxxxxxxxxxxxxxkxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkxxxxxxxxxxxkkxkkkkkkkkkkkkkkkkkkkkkkkxkkkxkkkxxxxkkkkkkkkkkkkkkkkkkkkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxdxxkkxxxo:,,''',,'.'''''''''''..'''.....................................  ...........,coxxxxxxxkkkkkkkkxxxxkkxxxxxxxxxxxxxxxxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddxxkkkxx
xxxxxxxxxxxxxxxxxxkkkxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkxxxxxxxxxxxxxkkxxkkkkkkkkkkkkkkkkkkkkkxxxxxkxkkxxkkkkkkkkkkkkkkkkkkkOOkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkkkkkkkkkkkkkkkxxxkxxxxkkxxxoc;''...'''''..''''''..........................'''',,;;;;,,,''..............'...;ldkkkkkxxkkkkOkkxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxddddddddddxkkkx
xxxxxxxxxxxxxxxxxxxkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxkkkxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkOOOOOOOOkkOOkkkkkkkkkkkkkkkxkkkkkxdl:,''...'..'''....'''.............   ......',,;;;;:::ccccc::;;,,'.............'...,cdxkkOkxxkkOOOkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddxxkk
xxxxxxxxxxxxxxxxxxxxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkxxxkkkkkkkxkkkkkkkkkkxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkxoc:,'...........''...'............ ......',;;:::cccllllllllllcc::;;,''............''.'coxkkkkxxkOOOkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdxxxxxxddddddddddxk
xxxxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkxkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkkOOkkkkkOOOOOOkkkkkOkkkkkkkkkkkkkkkkkkxoc:;'''..'.............................',;;::ccccllllllllllllllllcc::;,,'...... ...'''.':ldxxxxxkkkOkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxxxxxxddddddddddx
xxxxxxxxxxxxxxxxxxxxxkxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkxxkkkkkkkxxxkkkkkkxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkOkkkkkkkOOkkOOOOkkkkkkkkkkkkkkkkOkkkkdc;,,'''''............................',,;;::cccclllllllllooooooolllccc:;,''..........'..':oddxxkkkkkOkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddd
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkxxkkxxxxxxxxxxxxxxxkkkkkxxxkxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkxkkkxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdc:,''.''''...........................',,;;:::cccclllllooooooooooooollllcc:;,'.............':dxxkxkkOOOOkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddd
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxkkkxxkkkkkxxxxxxxxxxxxkkkkkkkkkkkkkxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkkkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkxl:,'.'''''''''.......................',,;;:::cccclllllooooooooooooooooollcc:;,'...  ........':dxxxkkkOOOkxxxxxxxxxxxxxxxxxxkkxxxxxxxxkxxxxxxxxxxxkkOkOkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdxdddd
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkxxkkkkkxxxxxxxxxxkkkkkkkkkkkkkkkxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkOOOOOOOOOOOOkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkoc;'''''',''''......'......... ......'',;;;:::cccclllllooooooooooooooooollcc:;,....  .........':oxxxkOOOOOkkkkkkkxxxxxxxxkkxkkkxkkxkkkkkkxxxxxxxxxxkOOOOOOOOOOOkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd
dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkxxxxxxkkkkkkkkkkkkkkkkkxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOkkOkkOkkkkkkkkkkkkkkkkkkkkkkkdl:,,,,,,,',,'''...''........  ......'',,;;;:::cccccllllooooooooooooooolllc:;,'.................':oxxkOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxkkkkkkOOOOOOOOOOOOkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dddxxxddxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkxxxxkkkkkkkkkkkkkkkkkkkxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOkkkkkkkOOkkkkkkkkkkkkoc;,',,;;,''',''''''........   .....'',,;;;;:::::cccclllllloooooooooollllc;,.....''''............,:oxkOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ddddddxxxxxxxxxxxxxxxxxxxxxxxxxkxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkkxkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkOOkkkkOOOOkkkkkkkkkkkkkkOOOOOOOOOOOOO0000000OOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkxc;,',,,,,,,,,',''''.......    ......'',,;;;;::::::ccccccllllllllllllllllc;,..'''''''..............,:okOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dddxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkkkkOkkkOOOOOOOOOOOOOOOkkkkkkkkOkkkkOOOOOOOOOOOOO000000000OOOOOOOOOOkkkOOOOOOOOkkkkkkOOko:,,;,,,,,,,,,'''''......      .....'',,,,;;;;:::::ccccc::::::::cccllllll:;,,,,'',,,,'..............;okOkOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOkkkkkkkkkOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkOOOOOOOkkkkkkkdc;,,;;;,,,,,,,''''......       ......',,,;;;;;;;;;;,,,,'''''',,;::cccllllc:;;,'',;,'...   ...,'.....':dOOkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxxxxxdxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOkkkkkkkkkxxxxoc;;;;;,,,,,,,''''......        ......',,,,;;,,''..........''',,;;;:ccllllc:;;,'''......... ..',.....',ckOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkxl:,,,;,,,,,,,''''.....          ......''',,'.........'',,,,,,,,,,,,;:ccllll:;;'...  ...''......,'....,,;dOOOOOOOkkkkkkkkkkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkxxxxxxxxxxxxxxxxxxx
kkkkkkxxkkkkkkkkkkkkkkkkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00O00OOOOOOOOOOOOOOOOOOOOOOOkxxoc;,,,,,,,,,,'''''......         .......''......'',,;;;;;;;;;;;;;,,,,;:cclolc:;,..   ...'.......''....,,'ckOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkkOOkkkkkkkxxxxdddxxxxxxxxx
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000OOOOOOOOOOOOOOkxddo:,,,,,,,,,,'''''.......        .............'',,;;;;;;;;:::::;;;,,',,,;:clolcc:,''.''''''''...........'',dOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxxxxxxxxxxxxxxx
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOkkkkkkkkkkOOOOOOOOOOOOOOOOOO000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOO000OOO000000O0000000OOOOOOOOOOOkxxdxxxo:,,,,,',,,'''''........       .............'',;;;,,,;::c::::::;;,,,,,,;:cllolcc:;;;;;;;,,,''..........'''lOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkxxxxxxxxxxxxxxx
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOkkkkkkkOOOOOOOOOOOOOO0000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00O0000000OOO00000000000000OOOOOOOOOOOOOOOOOOkkxxxxxdl;,,,,'',''''''........         ...........'',,,,''''''...',,,,,',,;;,,;;:clloolcccccc:::;;,,'''.......,'.:kOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkxkxxxxxxxxxdd
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkOOOOOOOOOOOOOOOOOOOkkkkOOOOOOOOOOOOOO00000000000000000OOOOOOOOOOOOOOOO0OOOOOOOOOOOOO000000000000000000000000000000OOOOOOOOOOkxxkkxxxxdl;,,,''''''''..........        ............''''''....   ..';loc;,,,;;;;;;::ccloolllllcccc:::;,,'.......,,.,dOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkOOOOOOOOOOkkkkkkkkkkkkkkOOkkkkkkkkxxxxxxx
kkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000OOOOOOOOOOOO000OOOO0000OOO0000000000000000000000000000000000000Okkkxxkkxxdxkdc,,,''''''...........          .............'....       ...,cc:;;;;;;;:::::::loooooollllcccc::;,'......,,.'oOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxkkkOOOOOOOOOkkkkkOOOkkkkkkkkkkkkkOOOOOOkkkkkkkkkxxxx
kkxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000000OOOOOOOO000O000000000000000000000000000000000000000000OOOkkkkkkkkkkkxkkkdc,'''''............             ..............     ........,,;;;;::::::::::::clodddddoollcccc:;,''....',,.'lkOOOOOOOkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxkkOOOOkOOOOOOOkkkkkkkOkkkkxxkkkkkOOOOOOkkkkkkkkkkkxx
xxxxxxkkkkkkkkkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00O000000000000000000000OOO000000O0OOO000000000000000000000000000000000000000OOOOOOOOOOOOOOOOkxl;,'''.............              ........''''''........''',,,;:::cc::::::::;;:ccooddddddlccccc:;,,'...'','''lOOOOOOOOkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkOOOOOOOOOOkkkkkkkkkkkkxxxxkkkkkOOOOkkkOOOkkkkkkk
xxxxkkxxxkkkkkkkkxxkkkxkkkkxkkkkkkkkkkkkkkkkOkkOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000000000000000000000000000000000000000000000000000000000000OO000OOOOOkxo:,'''.............               ........''',,,,,,,,,,,,;;;:::cccccccc::::;;;;::ccllllllccccc::;,''....'''',oOOOOOkOOkxxxxxxxxxxxxxxxxxxkxxxxxxxxxxxxxkkxxxxxxxkkkkOOOOOOOOOkkkkkkkkkkkxxxxxkkkkkkOOOOOOOOOOOOkkkk
kxxxxxxxxkkkkkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000000000000000KK000000000000Okkkkdl;,''............                  ......'''',,,,;;;;;;::::::ccccccccccc::;;;;;;;;;;;::::;:ccc:;,''.......'',oOOOOOkkOkkxkxxxxxxxxxxxxxxkkxxxxxxkkkkkxxkkxxkkkxxxkkkkOOOkOOkkkkkkkkkkkkkxxxxxxkkkkkOOOOOOOOOOOOOOkk
xxxxxxxxkkkkkkkkxxkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000000000000000000000000000000000000000000000000KKKKKK00K000000000Okxxdl:,'..............                  ......''''',,,;;;;;;:::::ccccccccccc:::;;;;,,'..',,,;;;::c::;,'........'';dOOOOOOkkkkxkxxxxxxxxxkkkkxxxxxxkkkxxxxkxxxxkxkkkxxxkkkkkOOkkkkkkkkkkkkkkkxxxxxxxkkOOOkOOOOOOOOOOOOOOO
xxxxxxkkkkkkkxkkkkkkxxkkkkkkkkkkkkkkkkkkkkkkOOkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000KK0000KKK0K00000000000000kdolc;'..............                    ......''''',,,;;;:::::::c::cccccccc:::;;,,,'...'',,;::::::;,..........'':xOOOOOOOOOkkkkkkkxkkxkkkxxkxxxxxkkkkxxxkkkkkxxkkkxxxkkkkkkkkkkkkkkkkkkkkxxxkkkkkkkkOOOOkOOOOOOOOOOOOOO
xxxxxxkkkkkxxkkkkkkkkxkkkkkkkkkkkkkkkkkOOOOOOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOkkOOkOOOOOOOOOOOOOOOOOO0OOO0OO00000000000000000000000000000000000000000000000000000000KK0000K0000000000KK0000Okoll:''.............                     ........'''',,,;;;;;:::::::::cccccc::::;;,,''',,,;;;;::;;,'...........''ckOOOOOOOOOkkkkkkkkkxxkkkxxkxxxxxkkkkxxxxxkkkxxxxkxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOO
xxxxxxkkkkkkkkkkkkkxxxxkkkkkkkkkkkkkkkkkkkkOOOOkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000OOO00000000000000000000000000000000000000000000000KKKKKK0KKKKK00KK0KK0000000KK00000kol:,'..............                      .........'''',,,;;;;;;:::::::::::::::::::;;;;;;::::;;;,'.........'...',oOOOOOOOOOOOkkkkkkkkkxxkkxxxkxxxxxkkkkkkkkkkxxxxxxxxxxkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOO
xxxxxxkxxkkkkkkkkkkkxxkkkkkkkkkkkkkkkkOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000000000000000000000000000000000000000000000KKKKKKKKKKKKK0KKKKKKKKKK000KKKK00xl:,''.............                       ..........''''',,,,;;;;;;;::::::::::::::::::::::::;,,'...............';dOOOOOOOOOOOkkkkkkkkkkkkkkxxkkkkkkkkkkkkkkkkxxxxxxkkkxkkkkkOOOOOOOkkkkkxxxxxkkkkkkkkkOOOOOOOOOOOOOOOOOO
xxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OO00OOOOOOOOOOOOOOOOOO00000000000000000000000000000000000000000000000000000000000000KKKKKKKKKKKKKKK00KKKKKKKKK000KK00Oxc;''.'...........                         ............''''',,,,;;;;;;:::::::::cc::::::::;,...................'':xOOOOOOOOOOOOkkkkkkkkkkkkkxkkkkkkkkkkxxkkkkkkkkxxkkkkkkkkOkOOOOOOkkkkkkkkxxxkkkkkkkkkOOOOOOOOOOOOOOOOOO
xxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000OOOOOOOOOOOOOO00000000000000000000000000000000000000000000000000000000KKK0000000KKKKKKKKKKKKK0KKKKKKKKKK00000000Od:,''............              ..           .............'''''',,,;;;;;;;;;::::::::::;;,'........  .........';,,lkOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOk
xkkkkkkkkkkkkkkkkkkkkkkOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOO0OO0000O000000000000OOOOOOOO00000000000000000000000000000000000000000000000000000000KKKKK0KKKKK0KKKKKKKKKKKKKKKKKKKKK000KK0000K00xl;,''...........   .          ......    .    ..............''''',,,,,,,;;;;;;;;;;;;,,,...........    ......'cc';xOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOk
kkkkkkkkkkOkkkkkkOOkkOOOOOOOOOOOOOOOOOOOOOO00000000000000000000000000000000000OOOO0000000000000000000000000000000000KKKKK000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KK00Oo;,,'...........   .           .......    ..   ...............'''''',,,,,,,,,,,,,,,''.........  ..    .....;lo,.ckOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOO
kkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000000000000000000OOOOO00000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000KK0Od:,,,'...........   .            ..............   ...............'''''',,,,,,,,,,,''.........         ....':ldc.'xOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOO
kkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000KK000000000000000OOOOO000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00Okl,,',,'..........  .              ...............  ................'''''''''''''''...............    ...';:ldo,.ckOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkkkkOkkOOOkOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000KK0KK00000KK000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000x:,,'.,,..........  .                ............    ...................'''.''''''.............  . ....',::ldd;.;xOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000KKKKKKKKKKKKKK000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000Ol,'''.'''........  ..                   .. .....       .................'..........................',;;:::lodc.'dOOO0OOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000KKKKKKKKKKKKKK00000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00d;''....'.........  .                      .              ....................''.'........''''''',,;;::::clldl'.lxOOOO00OOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOO0000OOOOO00000OOOOOOOOOOOOOO00OO0000000000000KK0KKKKKKKKKKKKKKKKKKKKKK000000000000000000K0KKKKKKKKKKKKKKKKKKXKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKOl,......''.......                           ..             .................''''''''''''''''',,,;;;::::::cclc'.;odkOOOOOOOOOOOOOOOOOOOOkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOO00000000000000000000OOOOOOO0000OO00000000000000KKKKKKKKKKKKKKKKKKKKKKKKK000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKXXKXKKKKKXXKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXKKXXKKKXKKKKKKx:''.....''........                           ...            .................'''''''''''''''',,,;;;;:::::::;...;ldkkkkkkkkkOOOkOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000
OO00000000000000000000000OO00000000000000000000KKKKKKKKKKKKKKKKKKKXKKKKKKK00000000000000KKKKKKKKKKKKKKKKKKKKKKKXXKXXXXXXXXXXXKKKKKKKXXXXKXXKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXKKKKKKKK0o,..'...'''...........                          ....      ....................''''''''''''''''',,;;;;;::;,'....,:ldddxxxxxxxxkkkkkxkxdodlcdkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000000
OO0000000000000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKXXXXKKKKKKKK00000000000000KKKKKKKKKKKKKKKKKXXKKXXXXXXXXXXXXXXXXKKXXXXXXXKXXXXXKKKKKKKKKKXXXXXXXXXXXXXXXXXXXKKXXXKKOc'..''...''..........                                     .......................'''''''''''''',,,;;;,...  ..,;:codxxxxxkkkkkkkkkkxl;.....':dkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000
0000000000000000000000K000000KK00000000K000KKKKKKKKKKKKKKKKXXKKKXXKKKKKKKKKKKKK0000000KKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKd,...,'...''..........                                     ........................'''''''''',,,;;:cl:.    ..,:ccloodxxkkkkkkkkkkdc'.   .  ..,lxkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000
00000000000KK0000K0000KKKKKKKKKKKK00000KKKKKKKKKKKKKKXXXXXXXXXKKXXKKKKKKKKKKKKKKK000000KKKKKKKKXXKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOc...','...''.........           ..                          .....................'''''''''',,;;:cclll;     ..;c:clloooddxxxkkkkkkxdoc;'...   ..cxxxkOOOOkkkkkkkkkkkkOOkkkkkkkkkkkkOOOOOOOOOOOOOOOO0OOOOOOOOOOOO000000000000000
000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXKXXXXXXXXXXXXKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNXXXXXXXKd,....','''''..........            ..                         .................''''''''''',,,;;::cclll'     ..;:cclllllooddddxxxxxxxxddoc'..... .cxxxkkOOkkkkkkkkOOOkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOO0OO0OO00000000000000KKKKKKK
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXNNNNXXXXXXXXNNNNNNNNNNNNNNNNXNNNXXOc'.....,,'''''.........       ..                              ............'''''''''',,,,,,,,;;::cccllc.     ..':cccclllllooooooooooooolc:'........',:oxOOOOOOkkkOOOOOOOkkkkkkkkOOOOOOOOOOOOOOOOOOOO000OOOO00000000000KKKKKXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNXNNXXXXNNXXXNNNNNNNXNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNXXXd;'.....',,''''..........     .  ...                           .......''''''''''..''''.''';;;;;::cccll:..    ...;::ccccccllloooooooooll;.       .......;okOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000KKKKKXXXXXXXXXXXXX
XNNNNXXXXXXXNXXNXXXXXXXXNNNXXNNNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWNNNN0c;'......','.''..........                                        .....''',''''''...''''''',:c:;;:cccll:...   ...';:::ccccllllllllllllc:'         .......'cxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000O000000KKKKXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd:,........',..'.........                                           ...',;::::::c:cc:::::cclllllc::cccc:''...  ...,;:::ccccclllllllllcc;.           .......,dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXNNNNNNNNNXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOc;.........','.'.........                                          ..',;:cccccclllcclllloddddoolllccccc;'',........,;;:::cccccccccllcc:,.  ..        .......'dOOOOOOOOOOOOOOOOOOOOOOO000KKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd:'.........','''.........                                        ..,;:cccccccccccccclllloddxkxoccllccc:,';;,',''...',;:::cccccccccccc:;'.          .. .......,xOOOOOOOOOOOOOO000KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWNxc,..........','''.........                                       .,::ccccccccccccccclllllloodxkdccllccc:,;:c:;;;,,,'',;::ccccccccc::::,..           ..   ......:kOOOO000KKKKKXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMWWWWWWMMWWWWWWWWWWWWWWWWN0d:............',''........                                   ...',;:::::cccc:::::ccccllllloooodkdcclc:c:;,;cc:::;;,,,',;:ccccccc:::::;;.            ..    .......oKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNWNNNNNNNNNXNNWWNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMWMMMMMMMMMMMMMMMWMMWWWWWWWWWWWWKOx;.............','........                               ....',;::::cccccc:::::cccccllllllloodxkdc:ccc:;;,:lcccc:;;,',;:ccccc:::::::;,'.          ...     .......;0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNWWWNNNWWNNWWWNNNNNNWWNNWWNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWWWWWWWWWWWN0x:..............'',........                    .    .......,;::::ccccccccccccccclllllllloooodddxkdc;:c:;;;;clccc::;,,,;:ccccc::::::;;,.                    ...... .dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWNWWWWWWWWWWWWNNNNNWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWNKx:................','.......                        .....';::;,;:cllllcccccccclooddddooooooddxddxkdc,;:;;:;;clccc::;,,;:cclccc:::::;;,'.                    ...... .lKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNXXNWWWWWWWWWWWWWWWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMWMMWWWMWMWWWKo,..................''..........                .   ...',;:::;,.';ccccccc:cccclooddxxxxdddddxxxddxkdc,,:;;:;:cccc::;;;::cllcccc::::;;,'.                     ......  :0NXXXXXXXXXXXXXXXXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNXXNWWWWWWWWWWWWWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWWWMMMMMMWWW0c'..''...............''.........                 .....',;;;;;;;,',:c::::::ccclllloooddxkkxxddxxxdddxxc,,:;:c::ccc::::::ccllccccc::::;,''..                   ......   ;0NXXXXXXXXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNXXNNXXNWWWWWWWWWWWWWWWWWWNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMWXx;'.',,........  ......''.......                  ...',;::::::::;;;:::cc::::cccllllllloodxkkxddddddddxxc',::cc::ccc:::ccccccccc:::::;;;,'..                    ......   ;0NXXXXXXXNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK0
NNNNNNNNNNNNNNNNNNNNNNNNNNWWWWNNNNNNNNNNNNNNNNNNNWNNNNXXNNXXNWWWWWWWWWWWWWWWWWWWNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMWNOc''::,'.......    ......''.......             .....',;;,,,'''''''..''.''''''''',;:clllloodxkkxxdooddddxxl:cccc::llccccccccccccc:::::;;;,'.                      . ....  .:KNNXXXXXNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK000OOOO
NNNNNNNNNNNNNNNNNNNNNNNNNNWWWWNNNNNNNNNWNNNNNWWWWWWWWWNNNXXNXNNWWWWWWWWWWWWWWWWWWWNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc,,:cc,.........   ........''.....             ....',,,'...........................',:clodddxkkxdocldxddxdooooc:::cccccccccccccc:::::::;,'..                     .. ....  .cKNNNNXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK00OOOOOOOOOOO
NNNNNNNNNNNNNNNNNNNNNNNNNNNWWWNNNNNNNNNWWNWWWWWWWWWWWWWWNNKKXNXNWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWMWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXkc,;ldoc,.........  .................            ....',,'...............................';lddddxkkxdocldxddoddddoc;::cccccccccc::::::::::;,...                     ... ..    .lXNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK00OOOOOOOOOOOOOOOOO
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNNNWWWWWWWWWWWWWWWWWWWNXKKNNXNWWWWWWWWWWWWWWWWWWWWWWWNNNNWWWWMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKkc,;okkxc'......... ..................             ....;;'.................................'cdxddxkkxdlccoddl::oxxo:::clccc::::::::::::::::;'                                  .oXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK000OOOOOOkOOOOOOOOOOOOOOO
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNNNNNWWWWWWWWWWWWWWWWWWWWWWNXKXXNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNWWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKxc;:okOkkl'............'................       .  .......;;............................ ......:dxxxxkkkdlcllcloc,:xxl:::cl:::::::::::cccc::::;..                                 .dXNXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK000OOOOOOOOOOkOOOkOOOOOOOOOOOOOO
NNNNNNNNNXXXNNNNNNNNNNNNNNNWNNNNNNWWNNNWWWWWWWWWWWWWWWWWWWWWWWNXKKXNNNWWWWWWWWWWWWWWWWWWWWWWWWNNNNWWWWWWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0dc:lkKK0Ox:............','................     ... ........,;'............... ..........   .....:oxxxxxkkxoooccloo::xxl:::cc::::::::ccccccc::::,..                                .,kNXXXXXXXXXXXXXXXXXXXXKKK0000OOOOOOOOOOOOOOOOOOOkkkOOOkkkOOOOOOOO
NNNNNNNNNNNNXXXNXXNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWXKKKXNNWWWWWWWWWWWWWWWWWWWMMMWWWNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdl:cx0XK00Ol,............,;,.................   ..............,;'......... ..    ..  ........ .....;oxxxxxkkxdooolodxddxxc;;:cc:::::::cccccccc::::,.                                 .,ONXXXXNNXXXXXXXXKKK00OOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOOOOOO
NNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNWNNWWWWWWWWWWWWWWWWWWWWWWWWNXXKKXNNWWWWWWWWWWWWWWWWMMMMMMWWNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;cokXNXK0Od;.............c:,'..................................,;'.........          . .......  ....,oxxxxxkkxolllllxxddxxc,,;cl:::::ccccccccccc:c:,.                                ..:0NXXXXXXKKK000OOOkkkkkkkkOOOkOOkOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOO
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWNXXKKXNWWWWWWWWWWWWWWMMMMMMMMWWWNNWWWWWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xl:;cok0XXXK0Od:.............'ll,,'... ..............................';,........             ....... .....,oxxxxxkxoloodlldxodkxoc:cccc::::cccccccccccc::'                                 ..oKKK000OOOOOOOOOOOOkkkkkkkOOOkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNWWWWNNNNWNNWWWWWWWWWWWWWWWWWWWWWWWWWNXKKKXNWWWWWWWWWWWWMMMMMMMMMMWWWNNWWWWWWWMWWMMMMMMMMMMMMMMMMMMMMWXKOxo:;:lxOKKKKXK0ko;..............'ldc,,,..................................';,........             .......  ....,lxxxxxxocloxdlldxxxxdc:cc:cc::::cccccccccccc::,.                           .   ..:kOOOkkOkkOOOOOOOOOOkkkOOOkkOkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000
NNNNNNWNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXX00KXNWWWWWMWWMMMMMMMMMMMMWWWNNNWWWWMWWMMMMMMMMMMMMMMWNKOxdl:,,;ldOKXXXXXNX0xl,............''.,dxoc;'....................',,,...........';,........            .......   ....,lxxxxxd:,:oxxlcdxxdoddldxoccc::ccccccccccccc::'                        .      ...oOOOOOOOkkkOOkOOOOkkkkkOOOkkOOkkOOOOOOOOOOOOOOOOOOOOOOOOO000KKXXXNN
NNXXNNNNWWNWWWWNWWNNWWWWWWWWWWWNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXKKKKNWWWWWWWMMMMMMMMMWWWWWWNNNWWWMMWMMMMMMWWNKOkdl:;,'';cox0XNNNNNNWN0dc,.............';',dkxxc,....................':::,...........';;.........          .......     ...'lxxxxxdc;;lxxocoxxxoddxxkkxxdl::ccccccccccc::;.                               ..lOOOOOOOOkkkkOkOOOOkkkkOOOOkkOOOOOOOOOOOOOOOOOOOOO0000KKKXXNNNNNNNNN
NNNXNXXNNNNNNNNNNNNNNNNNNNNNWWNNNNWNNNNNNNNNNWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWMWWMMWWNXKKKXXNWWWWWWMMMMMMMMMWWMWNNNWWWWNNX0kxdlc;,,,,;:ldk0XNNWWWWNNNXkl;'.............'::',dOO0x;'...................':lc:,''..........;;.............    ........       ..'lxxxxkxc;;lxxdccldxdooodxxxkkxdlccccccccccc::;.                              ..lO0OOOOOOOkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOO000KKKXXXNNNNNNNNNNNNNNN
NNNXXXNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWMMWWWWWWWWMMWMWWWWWWNXKKKKXNNWWWWMMWMMMMMWWNX0kxdol:;,',;:::codkOKNNWWWWWWWNXKOdc,...............;ol,;x00K0l,'...................,lc:;;,,,''.......,;'.......................        ..'cddxkkdc;;lddc,''cdxl:coddxxxxxxdlccccccccc::;.                              .oO000OOOOOOOOOkkkkOOOOOOOOOOOOOOOOOOOOOOO00KKXXXNNNNNNNNNNNNNNNNNNNNWN
WNNNNXXXXXXNNNXXXNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWNXKKKKKXXXXXXK0OOkdoc:;,,,,,;;:ldxkO0XXNNWWWWWWWWWXOxo:,'..'',''........,oxl;cx0KKXk:'....................,clll::c:,'.......,;'..................             ..'codxkd:,,;cl,....;oxo;;cldddxxxxxxdlccccccc::;.                             .lOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOO000KKXXXNNNNNNNNNNNNNNNNNWWWWWWWWWWW
0KXXNNNXXKKKXXXXXKKKKKKKKKKK0000000000KKK0KKKKKKKKXXXXXKKKXXXXXNNWWWWWWWWWWWWWWWWWWWWWWWWWNXKK0kdollc:::;;,,;;;;:ccoodxkkk0KNNWWWWWWWWWWNNX0dc;,'.',;::;,........'ckklcdO0KXX0l'.......'.............'cddolodl,'''.....,;,..........   ..                .,:oddxo:.',,,.. ...,lxxc;:clooddddddxxdlcccccc:;.                             .:kOOO00OOOOOOOkkOOOOOOOOOOO000KKKXXXNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWW
kxxxkkO00OOkkxxkO000000000KK000000000000000000OO00OOOOkxxkkxxxxxxxkkOOO00000000OOkkxxxdoolcc:;;;,,,;;:::::ccloodxk0KXNNWWNNXNNWWWWWNNXKOdoc;,'',;:cll:,''......'ckOdlxOOKXXX0o'.......................:ddddkxc',;''...''',;,......         ....         ..;lddddoc;''..    ..':ldc,;::clllllllloddolccccc;.                              .cOOO0OOOOOOOOOOOOO000KKKXXXNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
Okkxdllllllloddddxkkkkkxdddddddddddddddddxdddddddddoolc::;;;;;::::;;::cccccccc::::::::cccclllloddxkOO0KKKKKKKKK000000KKKKKKK0OO00Okxdl:,'''';;coddl:,'..'....'ckKOooOK00XXKKo'.........................cxkkxlcc::,'''.''';lc............   ....         ..;odddxxo;,'.      .',;;,',;::::cccclllloddlcccc;.                               .oOOOOOO00000KKKXXXXNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
xddddolooolllcccccccldxxkkkkkxxkkkxxxxxxkxxxxxxxxxxddddxxkkkkOOO00000KKKKKKKKKKKXKXXXXXXXXXNNNNNNWWWWWWWWWWWWWWWWWNNXXKKK00OOxoc:;,'''',,:ldkOkxoc,''.....''ckKKkokKK0KXXK0o,...........................,cdoodoc:;,;,'',';oo,.....    ...             ....;odddxo:;::;.     ..,''..',;:::ccccllllooddlccc;.                              ..;kKKKKXXXXNNNNNNNNNNNNNNNWWWWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
xxkOOkkkOOkkkxddolcccloxkkOOOOO0OOOO0KKKXKKKXKKKKXXXXXNXXXXXXXXXXXNNNNWWWWWWWWWMMMWWWWWWMMWWWWWWWWWWWWNNNNNNNXXXXXXXXXXKK0kdl:,',,,,;:coxOOkdl::;,''.....,cxKXkxkKXKKXXXXOc.......................... ....,lddo:;;:::;;;,;oo,........ ..               ...;ooooc:;;;:lc.    ..';'..,,;::::ccccclllodxoccc,                     .   ...  ..:xKNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWNWWN
kOOOOOkkkkkxxxxxxddddlc:coxO0KXNNWWWWWWWWWWWMMWWWWWWWWWWWNNNNNXXXKKKKKKKKKXKKKKK0KK00KK000000000000KKKKKK000000000OOkxdlll:,,;;;:codxxkxxddolcc:,'...'',cxKX0kx0XXKKXKKOo;......'...........................:ll:;clodc::;:oo;...........               ...,lll;.';;;:cl;.    ..,...,;;;:::::ccccllodddlc:'                     ..  ...;lx0XNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWNNNNN
ooddooddxxkO00KKKK00OOxollldxkkkOO00KKKXXXXXNNNNNNNNNNNNWWWWWWWWWWWWNNWWNNNNNNNXXXXKKKKKK000000000000KKKKKK0Okkxdol::;,;;:ccooolodddodxddxxdl:,''''',:lkKKOkkOKXK0000Od;''..'''..............................',;:ldxdllc:coo:..........               ...;clc;..';:::cl:.      ....,;;:::::::::cclloddlc:.                 ........',lKWNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNN
xxxddddddxdxxxxxxxkOOOkxdolcokO0OOOkxxkkO00KXNNNWWWWWWWWMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNXKK0Okolll::;;;:clooooooloddxkOOkkxoc:,'''',;:lxO0OxxkkOOkxxxxdc,.'.......................................,ldxocllloddoc'.....                  .'coll;....;::::c:.       ...',;::cc::cooddxxdodoc;.     ........''''',,;;;;::ckNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWNNNNWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNN
XXKK0OkxdxkkkkxxdddddddddoolccldxxkkkxxxdddddxxxkkOO0KKXXNNWWMMMMMMMMMMMMMMMWWWWWWWWWWWWNNNNNNXK0Okkxdlcc:::;;;;;;::clloddxkxkkOOOkkxdoc:,'''''',:ldxxocccllc:;;;,,''......................'.....................';c::lolloxxd:......                 .'clc;.. ..;;;;::'        ....';::cc::codddxxkxddc,.    ...'',,,,,;;;;;::::::cdKNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNWWWWWWWWWNNNWWWWWWWWWNNNNNNNNNNNNNNNNN
MMMMMWWWX0000KXXNNXXK00OOkkxxdlc:codddooodddoollccccccccloodxxkkOO00KKKKXXXXXXXXXXXKK000Okkxdolc::;;;;;;::cloddxkOO000KKXXXXKK0Okdlcc:;'''''''.''',,'''''...........................................................',:clllxxdo:'...                  .';;'... ..,,,;;'.      ...c:..',:ccc:clooooddkkxl.  .  ..'',,;;;;;:::::::::clONNNNNNNNNNNNNNNWWWWNNNNNNNNNNNNNNNWWNWWWWWWNNNNNNWWWWWWNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMWNKOOO0XNWWWWWWWWNXK0kolok0KKK0K000O00000OOkkxxdddoolc:cccclccllllccccc::::;;;;;;:cclloodxkkO00KXXNNNNNNXXXK0Okxdolcc:;,,''''''''',:cc::ccclodoool:;'.........................................................,codxdddl:'...             ..............,,','.        .,dd;..',;cc::clllooodxko. ..  ..',,;;;;;:::::::::ccxXWNNNNNNNNNNWNNWWWWNWWWNNNNNWWWWWNNWWNNWNNWWNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMWX00O0KXNWMMMMMWWWWNKxoox0KXXXXXNNNNNNNNNNNNNNNNXXKKKKKKK0OOkkkxdddddddxxxkkOO0KXXNNWWWWNNNNNNXK00kxxdol::::;;,,;;,,,'',,,,,;lxO000OO0KXK0kdoc;,'..........................................................:ddddddddool:;,...........'..............'..'.        ..;dxl;'.',;::::ccllooodxx;.   ..',,;;;;;:::::::::cco0NNNNNNNNNWWWWWNNNNNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMWNK0OOOO0KXNWWMMMMMWWN0xdx0XXXXNNNNNXNNNWWWWWWNNWWWWWWWNNNNNNNNNNNNWWWMMMMMMWWWWWWWNNXKK0Okxdoolccccloooddolc;;,''',;,,,:lx0XXX0OkkOOkxl;;;'..........................'.............................'....:ddddddddddddddoolccc:::::::,. .. ........,'','.........,:oolc:,'.',,,;;::cclllod;.  ...',,;;;;::::::::::clONNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMWWXKOO00OOO0KXWWMMMMWWNKkdxKNWWWWNNNNNNNNXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKK0OOkxdoooolllloxxkO00KXXK0ko:;,,,,,;::::lxOXXKOxxdddlc:;,''..........................''''.........'...................''...cdddddddddddddddooooooolllcc;. ...........,;;,;:cccccllllloooool:'...'',,,;;;:::;.  ...'',;;;;:::::::::::cxXWNNNNNWNNNWWWWWWWWNNNWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMWNK0O0KXK00KKXNWMMMMMWX0kkOXWWWMMMMWWNNNNNNXXNNNWWWWWWWNNNNXKKK0OOkkkkxkkxxxkkkkO0000KKKKXNWWWWKOxl:;;;;;;:;;;:cdOKK0Oxdocc::;,'............................',:;,'''.............................,'.'lddoooodddddddddooooooollllc;. ...  ......;;;;:cccccclllllloooolc:,...,,'',,,,'.    ...',;;;;::::::::::::oKNNNNWWWWWNNWWWWWWWWNNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMWWWWXOO0KXXXK00KKXWWMMMMWX0kOKXNWWWWNNNNXXXK0OOkkxxddddddddddddxkOO00KXXXXKKXXNNNNWWWWWNNWNX0xlc:cooddocc:;;coxkkkkxoc::;,''.............................',;;::;,'.......................  .. ..,:;''cdolccllooooodddoooooooololl;.....   .....,;;::ccccccccllllllllllcc;,,cl'...       ...',,;;;::::::::::::lONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMWNK0O0XNWNXKKKXXNWWWWNX0xdxxO0000KKK0000OkkkkkkkkkkO000000KKKKKK00KKXXXNNXXXK00000OkdooodxkkOOkdl:;:coxkkxdlc:;:;,,'''...........................,;;:::;;:;,..'..................     .....';::,,;::ccccllooddddoooooooooool:.           .,;:::::::cccccccccccccllcc:;cc.         ...'',;;;;:::::::::::cxXWWWWWWWWNWWWWWWWWWWWWNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMWWXKOOKXNWWNX0kkkO0KKXXX0Oxk0XNNNXXXNXXXXNNNNWWWWWWNNXXXXKKKKKKKKXXXKKKKKKK0kxoccldOKXXKOkkdl::ccloolc;;;::;;;,'''...............'.........',cooc;;;;,;:;,..'.................       .   ..':c;'.';cllccllodddoooooooooolc:'............,;;:::::::::::::::::cccccc::c,.        ....',,;;;;:::::::::::oKWWWWWWWWWWWWWWWNNNNWWNNNNWWWWNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkddkO00KXXXXXK00KKXXK0OOkkOKNWWWWMMMMMMWWWWWNNWNWWWWWWWWWWNNNXXXK0OkdoodkO0XNNNNKOxdc;;;:lllcclollc:,'''''.........'.......'.......,cxOOdc;;;;;,;:;,.......................        ....,;:,..:oollccclodddoolloollc:;;;,,,,;;;;;;;;;;;;;;;;:::::::::::::cccc::'          ...',,;;;;;::::::::::lONWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMWNNXKK0kxdoxOKXNNNNNXKK000KXNXK0kkxkkO0KXNNNWWWWWWWWWWWWWNNXXXK00OOkkxdddxOKXNWWWWNNXOxl:;;;:cldddddol:,'''''.....';cc:,'...........'';lx0K0dc;,.';;,,;;;'........................     ........';;,colllcccccclloollllllc::;,,,,,,;;;,,,;;;;;;;;;;;::::::;;:::::ccccc,.       ...'',,;;;;::::::::::ckNWWWWWWWWNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMWWWMWWNX000OO0KXNXXX0kxdxOKXNNWWWWWNNNNNNNWWXK0OOOOOOO0OOO000OOOOkkkkxkkxxkkO0KXNWWWMWWWNXK0Okxo:;,;codxxddoc;,,,''..''.',:clc:,'.........',;cokKNXOd:,''..,;,',;;,'.............   ...   ..........   ....,cooolllllccccccllllllcc:;;,,,,,,,,,,,,,;;;;;;;;;;;:;;;;;;;::::ccclod:.      ...',,;;;;;::::::::::xXWWWWWWWWWNNWNNNNWNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMWWXKKK0O0KXXXXKXXNNNWWNX0OO0KXWWMMMMMMWWWWWWWWWMMMWWNNXK000OOO0KK000KKXXNWWMMMMWWNNNXXXK0O0Okxdc;;coxkkxoc:;'''..',;;;cllll:,'..........,:ox0XNNXOo;'''...',,'',,,,'...........       ..   ......     ..   'ldooollllllllllllllccc::;;,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;:ccllloodd,     ...'',,;;;;;:::::::::oKWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMWWNXXKKKXNNWWWWWWWWWWWMMMMMWWNK0OO0XNWMMMMMMMMMMWWMMMMMMWWWMMMMMMMMMMMMMMMMMWWWNXXK000OkkOO000Okkxc::cllc:;;,'''';::clodddoc;,'.......'';lx0XWWWNXOo;'''....',,'.',,,'.............        ..........   ..    ,ddoooooooolooooooollcc:::;;,,,,,,,,,,,,,,,,,,,,,,,,'',,,;;:cllllccclo,    ...'',,;;;;;;::::::::l0NNWWWWWWWWWWWWNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMWNNNNWMMMMWWWMMWMMMMMMWMMMMMWWWWNXKkddk0XWMMMMMMMMMMMMMMMWWWWWWNNNNNNNNNXXK0OkkkkxxkOOOO0KKXNNNXXKOl:;,,,''''',coodxkxxxdl;,''''.'''';cdOXWMMWWNKxc,'.......''''.'','''...............      .............      ,ddlooooooooooooooooollccc:;;,,''''..............'''',,;;:ccllllcc:cc:.    ...',,,;;;;;;;::::::cONNWWWWWWWWWWWWWNNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNWWWWWWWMMMWWWWNKxollx0XNWMMMMMMMMMMMMMMMMWNNNXXK0OOOkkkkO0KXXXNNWWWWWWWWNNX0Odc;,'''.''';loodxkxolc;'''..''.',cxKNMMMMWNKOd:,'.........'''..'''''......... ...      ...     ........      .,lolllooooooooooooooollllcc::;,,,,,,,,,,,,,,,,;;;;;::::cccclllcc::c;.     ..',,,,,;;;;;;;::::ckNWNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXNNNXNWWMMWWWMWNX0kxddxOKXNWWWNNXXXXXXXXKK0KXKXXXNNWWWWMMMMMWWWWWWWWWNX0kxoc:;''',:c:;,,,,;:;::,;,'.....',cx0NMMMMWNN0dc,'.'''........''...''''.........    .    .....      ...... .       .;lollllloooooooooolllllllcc::;;;;;;;;;;;;::::::::::ccc::ccccccc:,.     ..'',,,;;;;;;;;:::::dKNNNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNXXNWMMMMMMMMWWNKOxddxkkOKKXXXXXXXXXXXNNWWWWWWMMMWWWMWWWWWWWNXKOkxoc;,,'',:ldxxxxxxdooo:,,'......,:lkXWWMMMWNXOo:,'.....'.......'''...'''..........       ......     .     ......      .cdollllloodoooooollllollcc::::::;;;;;;;;;;::::::::::::::::cc:'.      ...'',,,,;;;;;;:::::oOXNNNNNNNNWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXXXNWWMMMMMMWWNX0Odlcloddxk0KNNNWWWWWWWNNNNNNNNNWWWNNXXK0Okdlc;,,,,,;:cokkOOOOO0KKOd:'''..',,cxKXO0WMMWNKkl;'''...''...............''...........       ..........          ...      .lxolcc::ccloddoollllllllc:::;;:::;;;;;;;;;;:::::::::::::::;'.   .    ..''',,,;;;;;;:::::lk0KXNNNNNWNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXXKKKKKXNNXK00OxollodxkO0KKXXXNNNNNNNNNNNNXK0kxdlc:,,;:;;;:ldxO0KKKKKKXKOo;''''';ldk00O0OkXWWN0xc,'''''''''...............'''.............     .    .....            .......'odllcc:;;;;:clllllccllcc:;;;;;;;;;;;;;;;;;;;;;;:::::;;;;:::;.. ...   ..''',,,;;;;;:::::cx000KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWNX0OkOkOKXXNWWWMMMMWXK0Oxddoooodxdxkkkkxxxxxdoolc:;;;;::;;;coxO0KKKKXXNNXOo:,''',:lx0XWWXkod0NWNOo:,'''.....................''.''..............  ..                        ..  .,ddolllccccccc:ccccccclc:;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;;;:cll,.... ....''',,,;;;;::::::oO000KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWWWWWMMMMMMWWWWWWWWNXKK00KKKKXXNNWWNNNNXKKKK0OOxddoldxdlccccc:;;;:lodk0KKKKKXXNNXOdc,'''';lxKNWNNKkodOXWXOl;,,'''.............'........'..'............... ...                             .cdollllllllllllcccc:ccc:;;;;,,,;;,,;;,,,,,''''''''',;;;::ccclc.... ....'',,,;;;;::::::cx0O000XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMWWNXXKKXXXXXXXXXXXXNNNNNNNXK00OOkxocccc::;:cokO00KKKKXNWWX0xc,'''':lx0XNWNKxodx0NWXOo;,,'''''.............'..................    .........                              .;lllllloooooollllccc:::;;,,'''''...........'',,;;;;;;;:::::cc'........'',,;;;:::::::coO00000KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMWWWWNNNXXKK0OOOkddddooolcllloxkO000KXNWWWNKOdl;,'',:lkKNNNNKkxdk0XWWNKxc;''''''''''..............................       .....   ..                            .;cloooooollllloolllc:;;,,'''''''''''',,;;;;;:::;;;;;;;;;::,... ....'',,,;;;:::::c:cx0000000XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWNNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXXKK00OOkxdddxxkOKXKKXNWMWWXOxl:;,,',;cxKNWWNX0kxkKNWMWNN0d:,''''''''''................................     ...... ...                               ..;coddoolllllllollc:::;;;;;;;;;;;;;;;;;:::::::;;;;;;;;,'.........'',,;;;::::::cclO0000000KNNNNNNNNNNNWWWWWWWWWWNNNNNNNNNNNWWWWWWWWWWWWWWNWWWNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNXXNXK00OkxdddkOOO0XNNNWWWWNKOdc;,,,,,:lx0XWWWX000KXNWMMWNNKkoc;''''''''''..................................   ...     ...                                  ..;looollcllllllc::;;;;;:;::;;;;;;;;;;::::;;;;;:::,...........'',,,;;::::::cccd000000000XNNNNNNWWWWWWWWWWWWWWWWWWNNNNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNXXXK0kxdoodkO0OO0KNNWWWNXKOxl:,,,,,;:okKNWMWNXXKKNNWMMMMWWNKxol:,'''''''''.......................................                                               ..;cllccllllc::;;;;;;;;;;;;;;;;;;;;;;;;;;;:ol::'..........''',,,;;:::::cccckKK0000000KNNNNNNWWWWWWWWWWWNWWWWWWWWNNWWWWWWWNWWWWWWWWWNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMWWWWWWWWWWNNNXXXKKXNNWWNNXOkkddddxO00000KXWWWNX0kdl:;,,,,,;:okKWMMWWWNNNWWWMMMMMMMWN0kxl:;,''''''''.........................................                                                 ..,:cclllc::;;;;,,,,;;;;;;;;;;;;,,''...cxc;;...........'',,,;;::::cccccl0XK0000000KXNNNNNNNNWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWNNWNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNXX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMWWWNNWNNNNNNNNNNWWWNX0OkdodxxkO0OOO0KXWWNKOxoc:;,',,,,;ldOXWMMMMWWNWWMMMMMMMMMMMNX00kc;;;,'''''''...............................   ...........                                                 ..';:cc:;,,,,,,,,,,,,,,'''....    ..:l:;,..........'',,;;;::::::ccccdXNKK0000000XNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNXNWMMMMMMMMWWWWWWWMMMMWWWWNXKOkdoolldxO0KOkxO0KXKOxdl:;,,,,,,,;:okKNWMMMMMMWWWWMMMMMMMMMMMWNXKXOl,,;;;''....................................    ..........                                                     .....';,..........            ..,;;;,.........'',,;;;::::::::cclkNNXK0000000KXNNNNNNNNWWWWWWWWWWWWWWWWNNNWWWWWWWWNNWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXNX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX00XXNNXXXNNWWNWWWWWNNXK0Okxddolcclloxkkkkxodxxdlc:;;,,,,,,;;coxOXWMMMMMMMMMWWMMMMMMMMMMMMMWNXXN0l;,',;;,'....................................  .    ....                                                              ... .............,;''..'',;;;;,......'''',,;;;::::::::cccoOXNNK00000000XNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNXX
MMMMMMMMMMMMMMMMMMMMMMWWWNWNNNNXX0O00OOOOkkxkkkkkkkxxxdoolllcccc:cccllllcccc:;;,,,,,,;;;;:ldk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNN0o;,''',;,'..''................................                     .                                                     ...;;,,,,,,,;;;xKkdlcc:;;;,;,.....''',,;;;::::::::::::cd0KNWXK0000000KNNNNNNNNWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXX
MMMMMMMMMMMMMMMMMMMMMMWNNXXXXK00Oxdxxxxxxddoollllllcc:::;;;:cccc::;;;;;,,,;;;;;::clllodxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWKo:,''''',,'...'..............................     ...              ..                                                     ...,;,,,,,,,;;;l00dolc:;;;,,'...'''',,;;;;::::::::::::cxKKXWNK00000000XNNNNNNNNNWWWWWWWWWWWWWWWWWNWWWWWWWWWWNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXX
MMMMMMMMMMMMMMMMMMMMMMMMMWNNXKKXK000000K0000OOkxddooollcccllllc::;;;;;:clodkkkxddxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNOl::;'..'''''...........................  .....                   ...                                                      .....;;,,,,,,;;;:kKkolc:;;,,,'.''''',,;;;;:::::::::::::lOKKKNNK000000O0KNNNNNNNNNNNNWNNNWWWWWWWWNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXX
MMMMMMMMMMMMMMMMMMMMWWNXXXXKKKKKKKKKXXXXXK0kxdolcclolllc:c::::codxkO00KXXKKOOOOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx:;,,,'....','..........................   ...   ..                                                                            ..,;,,,,,,,;;;o0Odlcc:;,,,''''',,;;;;:::::::::::::::dKKKKXWXK0000OO00XNNNNNNNNNNNNNNNWWWWWWNNWNNNNNWWWNWWNNNNNNNNNXXXXXNXNNNNNNNNNNNNNXXXXXXXXXXXXXX
MMMMMMMMMMMMMMMMMMMMMWWNNNNXXK0000kkkkkkkxddddooollcc::cldkOKKXWWWNNX0OOkO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNx:,''''....,,''.......... ..............  ...                                                                                    .',,,,,,,;;;cO0xocc:;,,,'',,,,;;;;:::::::::::::::cONXK0KNNK00000000KNNNNNNNNNNNNNNNNNNWNNNNWWWWWNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK
MMMMMMMMMMMMMMMMMMMMMMMMWWNNXXK0KK00KKKXXK00OkxdddxkO0KXNWWWNNXXKOOOkk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMWKo;,'''....'',''..............................                                                                          ..         .',,,,,,;;;;xKkolc:;,,''',,,;;;:::::::::::::::::l0WNK00NWX00000O000XNNNNNNNNNNNNNNNNWNNNNNWWWWNNNNNNNNNNNNXNNXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKXKKKK
MMMMMMMMMMMMMMMMMMMMWWWWWNXXXXXNNNNWWWWWNK0OkkOO0XNNNNNNXXKKK0000KXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMWMKo;'''.......'''''..................     ........                                                                        .           ..,,,,,;;;;l00dlcc;,,',,,,;;;::::::::::::::::::oKWNX00KWNK000OOO00KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKK
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXK0OkkO0KXXNNNXXXXXXXXXXXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWWWWWWWWWWWWWWWW0l,'.........'''''.................      ....   ....                                                                   ..       .......,,,,,,;;;:kKkocc:,'',,;;;::::::::::::::::::::xNWWNK0KNNK00OOO000KXNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXKKKKKKXXXXXXXXXXXXXKKKKKKKKKKKKKK
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0OOO00XNWWWWWWWNNNWWWWWWWNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWKo;'........''''''.................     ....                                                                                   ..   ....',,,,;;;;o0Odlc:,',,;;;:::::::::::;;;::::::ckNWWNK00XNX000OO00O0KNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKXXXXXXKKKKKKKKKKKKKKKKKKK0
MMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNXXNWWMMMMMMMMWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0l;.........'.',''.........................                                                                                      .   ....,,,,,;;;cO0xoc:,',;;;:::::::::;;;;;;::::::oKWWWWXK0KNNK00OOOOOO0XNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00
MMMMMMMMMMMMMMMMMMMMMWWNNNNNNWWMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMWMMMMMMMMMMMMWWMWWMMMMMMMMWWMWWWWWWWWMWWWWWWWWWWWWWWWWNWWWWWWOl;'.........'',''........................ .                                                                                           ..',,,,;;;;dKkol;',;;;::::::::;;;;;;;;::::::xNWWWWNK00KNX000OOOOOOKNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000
MMMMMMMMMMMMMMMMMMWWWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWWWWWWWWWMWWWWWMMMMMMMMWWMWWMMWWWMMWWWWWWWWWWWWWNNWNWWWWWNOc,'.........'','......................                                                                                            .     ..,,,,;;;l00dc,,,;;:::::::::;::;;;;;:::::l0WWWWWWX000NNK00OOOOOO0XNXXNNNNNNNNNNNXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000
MMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMWMMWMMMMMMMMWWWWWWWWMWWWWWWWNWWWWWWWWNNNNNWWWWOl:,.......'..'','.....................           .                                                                                .........',,,,;;:xKkc,,;;::::::::::::::;;:::;:::xNWWWWWWNK00XNX00OOOOOOOKXXXXNNNXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000000
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMWMMMMMMMMWWWWWWWMMWWWWWWWWWWWWWWWWNNNNNWWWXl;;,'.....''.'',''......................                                                                                             .........',,;;;o0k:,;;:::::::::::::;;;;;:::::cxXWWWWWWWX000XX0OOOOOOOO0XNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKK0000KKKKKKK00000000000000000000K
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMWWWWWMMMMMMMWWWWWWWWWWWWWWNNWWWWWWWWWNNNNNWWWNx;,''........'','.'......................                                                                                        ..   .....   .',,;,:Ok;,;;::::::::::::;;;::::::::ld0NWWWWWWNK00KNK0OOOOOOOOKXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKKKKKKK000000000000000000K
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMMWWWWWWWWWWMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNWNWWWNNWNNNNWWNWNk:''........',,'''.................  ..                                                                                          ....    ...  .,,;;;do,,;:::::::::::::::::::::::codkXWWWNNWNK0O0KK0OOOOkOOO0KXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKKKKKKKK0000000
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMWMMMWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWNWNNNNNNNWWWWNNNNNNNNNNWNx;'........','''......................                                                                                          ..   .   ... .,,,,;::,;:::::::::::::::;;;::::::loox0NWWNNNNK0OOO000OOOOOOOO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNWWWWNNNNNNNNNNNNNOc'..''...',,''............................                                                                                            .......',,;;,,;;::::::::::::::;;;::::::lddookKXKKK0000OOO000OOkkOOkkOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000KK0KK000
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWMMMWWWWWWWWWWWWWWWNWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNWKl'.''...',;'..................................                                                                                             ...',,;,,;::::::::::::;;;;;;:;;::cdxdoodOO00OOOOOOOkO00OOkkkkkkOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000000000000000
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNWWWWWWWWNNWNNWWWWWWWWWWWWWWWWWWWWWWWWWNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO:'''..',,'....................     ...........                                                                                          .....',,,,;:::::::::::::;;;;;;;;;;:oxxddooxOOOOOO00OkkO0KOOkkkkkkkOKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKKKKKKKKKK00000000000000000000
MMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMWMMMMMWWWWWWWWWWWWWWWNNWNNNWWWWWWWWWWWWWWWWWWWWWNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWXo,'',,,,'..................         .............            .......                                                                  ......',,,,,;::::::::::::;;;;;;;;:::lxxxddooxOKKKXXXX0OkkO00OOkkkkkkO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000KKKKKKKK0000000000000000000000
MMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMWWWWWWWWWNNNNNNWWWWWWNNNNNNNWNWWWWWWWWWNNNWWWWWNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWNk:,,,''''..................    .............                 .....                                                                    .......'',,;::::::::::;;;;;;;;;;:::cdxxxxdoodOXXK00OOOOkkk00OOOkkkkkk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKK00KKKKK00K00000000000000000000000
MMMMMMMMMMMMWWWMMMMMMMMMMWWWWMMMMMMMMMMWWWWWWWWWNNWNNWWWWWWWNNNNNNNWNNWWWWWWWWNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWNN0l;,,''.............................              ...  ..                                                                           ............,;::::::::::;;;;;;;;;;::coxxxxxddoox00OOOOOOOkkOO00OOkkkkkkk0KKKKKKKKKKKKKKKKKKKKKKKKK000000000KK000000000000000000000000000000000
MMMMMMMMMMMWWWWWMMMMWWMMWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWNNNNNNNNNK0Oo;,''..........................            ............                                                                            ............,:::::::::::;;;;;;;;;:::ldxxxxxddoodkOOOOOOOOOkkOK0OOkkkkkkkO0KKKKKKKKKKKKKKKKKK0KKKK000000000000000000000000000000000000000000000
MMMMMMMMMMMMWWWWMMMWWWWWWWWWWWWWWWWWWWWWNWWWWWWWNNNNNNNNNWWWWNNNNNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK00KNKl''.............................           ...........                                                                            ...........':::::::::::::;;;;;;:;::codxxxxxxdooox0KOOOOO00kkk0KOkkkkkkkkk0KKK0KKKKKKKKKKKKK0KKKKKKKKKKK000000000000000000000000000000000000000
MMMMMMMMMMMMWWWWMMMWWWWWWWWWWWWWWWWWWWWWNNNWWWWWNNNNNNNWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNXKKXNNWXd;'...............................         .......                                                                                  .........;::::::::::::;;;;;:::::cloodxxxxxdooodO00OOO0K0OkkO0OOkkkkkkkkO0K00KKKKKKKKKKK000000K00000000000000000K0000000000000000000000000000
MMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWNNNNNNNNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXNNNWW0l;'...'............................    ...... ............                   ...                                                     .......':::::::::::::;;::::::::cloodxxxxxddoookO0OOkkkkOkkkOOOOkkkkkkkk000000KKKKKKKKK00000000000000000000000000000000000000000000000000000
MWMMMMMMMMWMWWWWWWWWWWWWWWWWNNWWWWWWNWWWNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWKl,''''.....................................     .......                                                                                    .,:::::::::::::::::::::::ccloddxxxxxdooodkOOkkkkkkkkkkOOOkkxkxxxkO000000000KKKKKKK000000000000000000000000000000000000000000000000000
MWMMMMMWMMWWWWWWWWWWWWWWWWWNNNWWWNWWWWNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXOc,''......................................  .. .....                                                                                      ':::c:::::::::::::;:::::::cloddxxxxxddoloxOOOOOOkkkkkkOOOkkkxxxxkk0000000000000000000000000000000000000000000000000000000000000000000
MMMMMMMMMMWWWWWWWWWWWWWWWWWNNNNWWNNNNNNNNNNNNNNNNNNNXXNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWNNNNNNNNNWNNNNNNNNNNNXXXXXXXKx:'...........................................               .....                                                            ...........;::cc::::::::::::::::::;;:clooddxxxxddooldOOOOOkkkkkkkkOOkkkxkxxkkO00000000000000000000000000000OO00000000000000000000000000000000000
MMMMMMMMMMMWMWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXNXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWNWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXKo'.........................................             ....     ...                                                    ..............',::ccc:::::::::::::::::;,,:ccloodxxxxxddolokkkkkkkkkkkkkOOOkkkkxxxxkO00000000000000000000000000000000000000000000000000000000000000000
WWMMMMMMMMMMMWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNXXNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXO:'......................................                  .. ....                                                   .................';::cc::::::::::::::::::,',;:cloodxxxxxddoooxkkkkkkkkkkkkkOOkkkxxxkkkOOO000000000000000000000000000000000000000000000000000000000000000
MWWMMWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNXXNXXNNNNNNNNNNNNNNNNNNNNNNNNWWWNNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXKl''......................................                  .....                                                .....................,:cccc:::::::::::::::::,'',;:clloddxxxxxddoooxkxxkkxxkkkkkO0OkkxkkkkkkOOOO0000000000000000000000000000000000000000000000000000000000000
MWWMWWWMMWWWWWWWWWWWWWWWWNWWNNNWWWWNNNNNNNNNNNNNNNXXNNXXNNNNNNNNNNNNNNNNNWWWWWWWWWNNWWWWWWWWWWNNNNNNNNNNNNNXXXXNXXXXXXXXXXXXXXXXXXXXk:'................................  .. ...                                    .                             .......................':cccc:::::::::::::::::;,'',,;:cloodxxxxxddooodxxxkkkxxkkkkkOOkkkkkkkkkOOOO0000000000000000000000000000000000000000000000000000000000000
MMMMMMWWWWWWWWWWWWWWWWWWWWWWWNNWWNNNNNNNNNNNNNNNNNXXNNXXNNNNNNNNNNNNNNNNWWWWWWWWWWNNNWWWWNNNNNNNNNNNNNNNXNXXXXXXXXXXXXXXXXXXXXXXXXXXXx;...................................     .....                              ....                         .........................,cccc::::::::::::::::::;,,',,;:clloddxxxxxdooodxkxxxxxxxkkkkOOOkkkkkkkkkO000000000000000000000000000000000000000000000000000000000000000
MMMMMMMMMMMMMMWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNXXNNXXNNNXXNNNNWWWNNWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0l'.........................     ....    ...       .                    .....                            .........................':cccc::::::::::::::::c:;;,,,,;:ccloddxxxxxddoooxkkxxkxxxkkkkkOOkkkkkkkkkOO00000000000000000000000000000000000000000000000000000000000000
MMMMMMMMMMMMMMMMWWMMWWWWWWWWWNNNWNNNWNNNNNNNNNNNNNNNNNNXNNNNNNWNNWWWNNNWWWWWWWWNNNNNNNNNNNNNNNXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO:'.....................           ......      ......                    .                             ..........................;ccccccc:::::::::::::ccc:;,,,,,;:cloodxxxxxxdooodkkkkkxxxxkkkkOOOkkxxkkxxkO00000000000000000000000000000000000000000000000000000000000000
MMMMMMMMMMMMMMMMWMMMWWWWWWWWWWNNWNNNWNNNNWWNNNWWWWWNNWNNNNNNNNNNNWWWNNNNNNNNNNNNNNNXXNNXXXNNXXXXNXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXXXXXXXXKd,.....................            .   ........... ....       ...........                             .........................':cccccc:::::::cc::::cclc:;;,,,,;:cllodxxxxxxdooooxkkkkkxkkkkkkOOOkkxxkkxxkO00000000000000000000000000000000000000000000000000000000000000
MMMMMMMMMMMMMMMWWWWWWWWWWWWWWWNNWWWWWWWWWWWWNWWWWWNXNWWNXNNNNNXXNNNNNNXXXXXXXXXXXXXXXXXXXXNNXXXXXXXXXXXXXXXXXXXXXKKKXXXXXKKKKKKKKKXXXXXKx;......................              ........       .....................    ..                     .........................;ccccccc::::::ccc::::cllcc:;,,,,,;:cloodxxxxxxdoooxkOOOOOOOOkkkkOOkkkxxxxxkO00000000000000000000000000000000000000000000000000000000000000
WWWWMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNWNNNXXNNXXXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXXXXXKKKKKKKKKKKKKKKKk;................ ......            ....... .........'''''''''..........      .                    ........................,cccccccc::::::cc::ccclollc::;,,,,;:cllodxxxxxxdooldk0000000OOkkxkOOkkkxxkkxk00000000000000000000000000000000000000000000000000000000000000
WWWWMMMMMWWMMWWWWWWMMWWWNWWWWWNNWWWWWWWWWWNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXXXKKKKKXXKKKKKKKKKKKKKKKKKKKd,............................          .......''''''''''''''''..........  ..,,...                 .......................':cccccccc:c:::ccc:ccclddolcc:;;,,,;:clloddxxxxxddooox00000OOOOkxxkOOkkkkkkkkkO0000000000000000000000000000000000000000000000000000000000000
WWWWWMMMMWWMMWWWWWWMMMWNNNWWWWNNWWMMWWWWWNXXXXXXXXXXXXXXXXKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0d,...........................  ........'''''''''''''''''''''''''.........cO0K0o....               .......................:cccccccccccccccccccccdkdollc:;;,,,,;ccloodxxxxxxdooodO0000000OkkxxkOkkkkkkkkkO0000000000000000000000000000000000000000000000000000000000000
MWWWMMMMMWWMMWWWWNNWWWWNNNWWWWWNWWMMWWWWNXXXXXXXXXKKKXKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0o,.......... ...................''''''''''''''''''''''''''''''''........;OXKKKk;....             ......................;cccccccc::c::cccc:::ccdOxollcc:;,,,,;:cllodxxxxxxddoookOO00000OOkxxkOOkkkkkkkkkO000000000000000000000000000000000000000000000000000000000000
WWWWWWWWWNNWWNNNXXXXNWNNNXNWWWWNWWWWNNNNXXXXXXXKXXXKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKKKKKK00000K0o,....................'''''''''''''''''''''''''''''''''''''''''.........oKKKKK0o'....           .....................;ccccccc:::::::::cc::cc;lkkdollc::;,,,;::cloddxxxxxddooodOO00OOOOOOkxkOOOOkkxkkkxkO00000000000000000000000000000000000000000000000000000000000
NNNNNNNNNNNNXXXXXXXXNNXXXXNNWWWNNXXXXXXXXXXXXXXKXXKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKK00KKKKKKKKXXXXKKKK000KKKKK00000000Oc.........''''',,''''''''''''''''''''''''''''''''''''''''''''..'.......;OKKKKKKk;.....         ....................;ccccccc:::::::::::::cc:';xOxollcc:;;,,;;:cloodxxxxxxddoodk0OOO0OOOOkxxkOOkkxxxxxxkO00000000000000000000000000000000000000000000000000000000000
NXXXNNXXNNXXNXXXXXXXXXXXXXXXXXXXXKKXXXXXXXXXXXKKKXKKKK0KKKKKKKXXXXXKKKKKKXXXXXXXXXXXXXXKKKXXXKKKKKKKKKKKKK000KKKKKKXXXKKKKK0000000000000000000x,..''''''',,,,'''''''''''''''''''''''''''''''''''''''''''''''..........oKK0K00KOl'....        ...................;cccccccc:::::::::::::cc,.'oOxdollc::;,,,;:ccloddxxxxxddoooxOOOOOOOOOkxxkkOkkxxxxxxxkO0000000000000000000000000000000000000000000000000000000000
NNNNNXXNNNNNNNXXXXKKKKKXXXXKXXXXKKKXXXXXXXXXXXKKKKKKKKKKXXXKXXXKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000KKXXXKKKKK0000000000000000000000d:,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''..........;OK0000000x;....       ..................,ccccccccc:::::::::::ccc:'..:kkdollcc:;;,,;::cloodxxxxxxddoodkOO0000OOOkxxkkkkkxxxxxxxO0000000000000000000000000000000000000000000000000000000000
NNNXXXXNXXNNXXXXNXXXXKKKKKKXXXXXXKKKKKXKKKKKKKKXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000KKKKKKKKK000000000000000000000000000Ol,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''..........oK00000000kc.....     .................':ccccccccc::::::::::cccc;...'oOxollcc::;,,;;:clloddxxxxxddoooxOO0000OOOkxxxkkkkxxxxxxxk0000000000000000000000000000000000000000000000000000000000
XXXXXXXXXXXXXXXXXKKKXXXKKKKXKKKKKKKKKKXXXKKKKKKKKXXKKKKKKKK00KKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXK00000000000000O00000000000000000O0Ol,''''''''''''''''''''''''''''''''''''''''''''''''''''''''''.........;OK00000000Ol'....    .................;cccccccccc::::ccccccccc:'.'..:kkdollcc:;;,;;:ccloddxxxxxxddoodOO00OOOOOOxxxkkkkxxxxxxxxO000000000000000000000000000000000000000000000000000000000
XXXXXXXXXXXXXXXKKKKKKXXXXXXKKKKKKKXXXXXXKKKKKKKKKXXKKKKKK0000KKK000KK00KKKKKKK00KKKKKKKKKKKKKKKKKKKKKXXXXK000000000000OOOOOOOOOOO00000000000000O00kl,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''..........o00000000000d,...     ...............,ccccccccccccccccccccccll;'''..,dOdoolccc:;;;;::cloodxxxxxxddoookO000OOOOOkxxkkOkkxxxddxxk000000000000000000000000000000000000000000000000000000000
XXXXXXXXXXXXXXXKKKKKKKKKKXXKKKKXXXXXKKXKKKKKKKKKKXXKK0000000000KKKKKKKKKKKK000K0KKKKKKKKKKKKKKKKKKXKKKK000O00000OOO0OOOOOOOOOOOOO00000OOOOOOOO000OOkl,''''''''''''''''''''''''''''''''''''''''''''''''''''''''..........;O0000000OO00d,....   ..............,clcccccccccccccccccccclllc,.''..:kxdollcc:;;;;;:clloddxxxxxddoooxOOO000000OxxxxkkkxxxxxxxkO00000000000000000000000000000000000000000000000000000000
XXXXKKKKKKKKKKKKKXKKKKKXXXKKKXXNXKKKKXKKKXKKKK00KKXKKK0KKKKKK0KKKKKKKKKKKK000KK0000KKKKKKKKKXKKKKKKK00000OOOOOOOOOOOOOOOO00OOO0OOO0OOOOOOOOOOO00OOOOkl'''''''''''''''''''''''''''''''''''''''''''''''''''''''''..........o00000000OOOOd,...... ............,clccllllllcccccccccclllllool,''..'okdoolccc:;;;;:cclooddxxxxxddoook000000000kxxxkkkxxxxxxxxO00000000000000000000000000000000000000000000000000000000
XKKKKKKKXKKKKKKKKKKKKKKXXXXXXNXKKKKKXXKKKKKKKKKKKKXXXXKKKKKKK0KK0KKKKKKKKK00KKKKK00KKKKKKKKKKKKKK0000000OOOOOOOOOOOOOO00000OOO0OOOOOOOOOO00OOO0OOOOOOkl'''''''''''''''''''''''''''''''''''''''''''''''''''''''''.........;O0O0000OO0OOOd,.................,clllllllllllcclllllllllllllooo;'...;xxoollcc::;;;;:clloodxxxxxxdoooxO00000000OkxxxkkxxddxxxxkO0000000000000000000000000000000000000000000000000000000
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKKKKKKKKKKKK000000000000KKKK00KKKKKKKKKK000000000000OOOOOOOOOOOOOOOOOOOOO000OOOOOOOOOOOOOOOOOOOOOOkc''......'''''''''''''''''''''''''''''''''''''''''''''''''.........o0OOOOOOOOOO00d'...............,lllllllllllllllllllllllllloooodo:'...lkdolllcc:;;;;:cclooddxxxxxddoldk000000000kxxxkkkxddxxxxxO000000000000000000OOOOOO0000000000000000000000000000000
XKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKKKK00KK0KK0K000000KK0KKKKKKKKKKK0000000000000000KKKKKK00KKKK00000000000OOOOOOOOOOOOOOOOOOOOO000OOOOOOOOOOOOOOOOOOOOOOOkc'''.'...'''''''''''''''''''''''''''''''''''''''.''''''''.........;k0OOOOOOOOOOOOo'.............,lllllllllllllllllllllllllloooooodd:...,dxoolllc::;;;::clooddxxxxxddoook000000000OxxxkkkxddxxxxxkO000000000000000OOOOOOOOOOOOOOOOO00O0000000000000000000
KKKKKKKKKKKKKK00000KKK00KKKKK00000KKKKKKKKK00000000KK0000KKKKK0000000000000000000KK00KK000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkc'''......'''''''''''''''''''''''''''''''''''....'''''''..........o0OOOOOOOOOOOOOo'...........,lolllllllllllllllllllllllllloooooodo;...cxdoollcc:;;;;:clloddxxxxxxddoodO00000000OkxxxkkkxdxxxxxxO0000000000000OOOOOOOOOOOOOOOOOOO0OOOO00000000000000000
KKKK00000000KK0000KKKKKKKKK0000000KKKK0KKK0000000000000K0KK000000000000000000000KK000000000000000000000000OO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOkc'.........'''''''''''''''''''''''''''''''..'...'''''''..........;kOOOOOOOOOOOOk;...........'lolllllllllllllllllllllllllllloooooodl'..'ldoollcc::;;;:cclodddxxxxxddoook000000000Oxxxxkkxxxxxxxxk000000000OOOOOOOOOOOOkkOOOOOOOOOOOOOOOO000000000O00000
KKKK00KKKKKKKKKKKXKKKKK00KKKK0K0000KK00000000K000000KKK0000000000000O0000000000KK00000000000000000000O00000000OOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOkkOOOOOkc'.............''''''''''''''''''''''''''''''''''''''''..........oOOOOOOOOOOOk:..;'........colllllllllllllllllllllllllllollooododd:...,ldoollcc::;;::clooddxxxxxdddooxO000000000kxxxkkkxxxxxxkO000000OOOOOOOOOOOOOkkkkkkkkkkkkkkkkxxkkOO0000000000000
KKKKKKKKKK00000KKKKKKK000KKK0000000000000000000000KKKK000000O0000O00O00000000000000000000000000000000000000OO0OO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkOOOkl'..............'''''''''''''''''''''''''''''''''''''...........;kOOOOOOOOOOl.'dOd,......:occllllllllllllllllllllllllllllllooodddd;...,loolllc::;;::clloddxxxxxxddoook000000000OxxxxkkxxxxkkO0000000OOOOOOOkkkkkxxxxxxxxxxxxxxxxxkxxxkkO0000O0000000
KKKK000000OOO000000000000K000000000000KKK000000KKK00000O000000000000000000000000000000000000000000000000OOOOO0000000OOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOkkkkOOOOOo'............'''''''''.''''''''''''''''''''''''''''............oOOOOOOOOOx,;xOOOd,....:olclccccllllllllllllllllllllllllllloooddxo'...'coollcc::;;:ccloodxxxxxxxdooox0000000000kxxxkkkxxxxkO00000OOOkkkkxxxxxxddxxxxxxdxxxxxxxxxxxkkkkkOOOO00000O00
000000O000000000000000000000000000000KKKKKKKKK00OOOO000OO0000OOOOOO00000000000000K0OO0000000000000000000OOOOO000OOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOkOkkkkkOOOOOo,...........''''''....''''''''''''''''''''.''''..'............;kOkkkOOOx:;xOOOOOd,..;olllccccccccclllollllllllllllllooolllooddxx:....'coollc::;;::clloddxxxxxxddoldO000000000OxxxxkkxxxkkkO00K0OkkxxxxxxxxxdddxxxxddddxxxxxxxxxxkxxxkkOOO000OOOO0
000000OOOO0000O0000KKKKKKK000000000KKKKKK0000000OOO0000OOOOOOOOOOO00000000O0OO000OOO0000OOO0000000000000OOOOOOOOOOOOOO00OOOO00OOOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOo,..........'''''''.''''''''''''''''''''...'''''...............oOOOOOOk:;xOOOOOOOx,.collccccccccclllooollllllllllllllooolllloodxd;.....;lolcc::;::clloddxxxxxxddooox000000000OkxxxkkxxxxkkOO00OkkxdxxxxxxxdddxxxxdddddxxxxdxxxxxxxxxxkkOOOOOOOOOO
000000000000OOOO00KKK000000000KKKKKKKK000OO00OOOOOOOO00OOOOOOOOOO0000OOO000OOOOOOOOOOOOOOOOOOOO00000000000000O00000OO00OOOOO0OOOOOOOOOOOOOOOOOOOOOkkkkkkkkOOkkOOd;...........'''''''''''''''''''''..'.....'..''...''..........:kOOOOOc.o0OOOOOOO0d:cccccccc::clllllooolooolllllllllllloooollllodl,.....,clcc::::::clooddxxxxxxdooldO00000000OkxxxxkkxxxxxkO0OkkxxdxxxxxxxxdddddddddddddddddxxxxxxxxxxxkOOOOOOOOO
000OOOO000O00000000000000000KKK0000000OOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000OO00OOOOOOOOOO0OOOOOOOOOOOOOOOOOkkkkkkkOOOkkOOd;................'''''''''''''''....'......''.'''''..........oOOOOo.,k0O0OOO0OOOko:::::c:::clllloooooooollllllllllllloooollccloo;.....':lcc::;::clloddxxxxxxxdoook0OOOOkkxxxdddxkkxxxxxxOOOkkxxxxxxxxxxxdddddddddddddddddddxxxxxddxxxkOOOOOOOO
0OOOOOOOOOOO00000000000000OO00000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000000OO000000000O0OOOOOOOOOOOOOOOOOOOOOOOOOOOO0x;................'''...''.....'....'.........''''...........;kO0x' :OOO00OO00O0Ol::::::;,,;:llllooooooollccllllllccclooolccccloo:......:cc:::::ccloodxxxxxxxdooodkkxxkkkkkOkdddxkxxxxxxkOkkkxxxxxxxxxxxxxxxddddddddddddoddddddddddxxkkkkkOOOO
00000000OOO0000000000OOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOO0000O0000000000000000000000000000OOOOOO00O00000OOOOOOOOOOOOOOOOOkOOOOOO00000x;.............'''''.....''...'....'''..'...'''..............o0O: .d00000000000kc:::::,.....;llloooooooolccllllolcc:cllllc::cclooc'.....;cc:::::clloddxxxxxxddoooxOkOOOOOOOkxddxxxxxxxxxkkxxxkkkkkkkkkkkxddddddooooooooooooodddddxxkkkkOOOOOO
OO00OOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkOOOOkOOOOOO000OOOOOOOO000000O0000000000000000000000000000OOOOOOOOOOO000000OOOOOOOOOOOOOkkOOOOOO000000x;.............''...'''..''..........''''''''''.............;Oo. 'k00000000000d:::::,...   'llloooooooocccclllllcc:cllll:,,:cllloc'.....,::::::ccloddxxkkxxxdooldOOkkkkkkkxxxxxxxxxxxkkkkkkkxxxxxddddddddddooooooooooooooodxxxxkkkkkkkkOOOOO
O0OOOOOO0OOOOOOOOOOO0000OOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOkkkkkkkOOOOOOOOOO0000OOOOOOOOO00000OO0000000000000000000000000000OOOkOOO00OO0000OOOOOOOOOOOOOOOOOOOOOO00000000k:.................'''.................''''''...............:'  l0000000000K0o::::;'....  'lllllooooolc:::::cccc::ccllc'..':clllol,.....':::::cclooddxxkxxxddoloxkxkkxxxxxxxxxxxkxxxxkxxxxxddddooooddoodddoooodddddxxxxxxkkkkkkkkkkkkkkkkkk
0KKK0000OOOOOOOO00000OOOOOOOOOOOOOOOOOOOOOOOOOOkkkkOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOO00000000000000000000000000000000OO0OOkkkOO00OO0000OO00OOOOO00OOOOO00OOOO000000000k:........................................''................  'kK0000000000Oo:::;,'..... .cllllllccc::::cccccc::::cll:.....;cclloc'.....';::::clloddxxxxxxddooodxxxdddddddddddxdddxxddddooddooooooooooooodxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkk
0K0000OOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOkkkOOOOOOOOOOOOOO0OO00OOOO00OOOOOOOOOOOO00000OOOOO00000000000000000000OOOOOOOOOOOOOOOO00000000OOOOOOOOOOO0OOOO00000000000k:......................................................... .l0000000000000d;;;;;'''... .:lllccc:::::::cccccc:;:ccllc'.....,cccll,......';:::cclooddxxxxxxddooodxdddddddddddddddxxdddoooooddoooooooooooodxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
OOOOOOOOOOO0OOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000OOOOOOOO00000000O000000000000000000000000OOO0000OOOOOOOO00000000OOOOOOOOOOOOOOOOO0O000000000kc.........................................................;OK00000000000KOc,;;,'lkc.. .:llcccccc:,,;::cccc:;;ccclll,.... .;cccl:........;::cclloddxxxxxxddooodddddddddoddddddxxddddoooooodoooooooooooodxkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkk
OOOOOOO0OOOOOOOOOOOOOkkOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00O0000OOO0OO00000000000000000000000000000000000000O0000000OOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOO00000000k;........................................................lKK0000000000000o,,,',xKO:. .:lccccccc;',:::cccc,,:ccccll;......':cclc'........;::cclooddxxxxxxdooodddddddooooddddxddoooooooooooollooooooooooxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
`

function setDoraASCII() {
    let codeSnippet = document.getElementById("code-snippet");
    let mainMock = document.getElementById("main-mock");
    let asciiArt = document.getElementById("ascii-art");
    let mainIntro = document.getElementById("main__intro");

    mainIntro.style.display = "none";
    codeSnippet.style.display = "none";
    mainMock.style.display = "none";

    asciiArt.style.display = "inline-block";
    asciiArt.innerText = doraASCII;
}
